CREATE DATABASE NET_QLKS
USE NET_QLKS

CREATE TABLE PHANQUYEN
(
	MAQ INT IDENTITY(1,1),
	CHUCNANG NVARCHAR(50),
	PRIMARY KEY(MAQ)
)
CREATE TABLE NHOMQUYEN
(
	MANHOMPQ INT IDENTITY(1,1),
	MAQ INT,
	PRIMARY KEY(MANHOMPQ),
	FOREIGN KEY (MAQ) REFERENCES PHANQUYEN(MAQ)
)
CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1),
	TENNV NVARCHAR(50),
	NGAYSINH DATE,
	TENTK VARCHAR(50),
	PASSNV VARCHAR(50),
	QUEQUAN NVARCHAR(50),
	SDT NVARCHAR(50),
	EMAIL NVARCHAR(50),
	DIACHI NVARCHAR(50),
	MANHOMPQ INT,
	PRIMARY KEY(MANV),
    FOREIGN KEY (MANHOMPQ) REFERENCES NHOMQUYEN(MANHOMPQ)
)
CREATE TABLE LOAIPHONG
(
	MALOAI INT IDENTITY(1,1),
	TENLOAI NVARCHAR(50),
	SUCCHUA INT,
	PRIMARY KEY(MALOAI)
)
CREATE TABLE PHONG
(
	MAPH INT IDENTITY(1,1),
	TENPHONG NVARCHAR(50),
	VITRI NVARCHAR(50),
	GIATHUE FLOAT,
	TINHTRANG NVARCHAR(50),
	MALOAI INT,
	PRIMARY KEY(MAPH),
	FOREIGN KEY (MALOAI) REFERENCES LOAIPHONG(MALOAI)
)
CREATE TABLE DICHVU
(
	MADV INT IDENTITY(1,1),
	TENDV NVARCHAR(50),
	GIADV FLOAT,
	PRIMARY KEY(MADV)
)
CREATE TABLE KHACH
(
	MAKH INT IDENTITY(1,1),
	TENKH NVARCHAR(50),
	CCCD VARCHAR(50),
	SDT VARCHAR(50),
	PRIMARY KEY(MAKH)
)
CREATE TABLE PHIEUDATPHONG
(
	MAPDP INT IDENTITY(1,1),
	MAPH INT,
	NGAYDAT DATE,
	PRIMARY KEY(MAPDP),
	FOREIGN KEY (MAPH) REFERENCES PHONG(MAPH)
)
CREATE TABLE CT_PHIEUDATPHONG
(
	MAPDP INT,
	MAKH INT,
	PRIMARY KEY(MAPDP,MAKH),
    FOREIGN KEY (MAPDP) REFERENCES PHIEUDATPHONG(MAPDP),
	FOREIGN KEY (MAKH) REFERENCES KHACH(MAKH),
)
CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1),
	MAPDP INT,
	MANV INT,
	MADV INT,
	NGAYLAP DATE,
	THANHTIEN FLOAT,
	PRIMARY KEY(MAHD,MAPDP),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MAPDP) REFERENCES PHIEUDATPHONG(MAPDP),
	FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
)
-- Insert dữ liệu cho bảng PHANQUYEN
INSERT INTO PHANQUYEN (CHUCNANG)
VALUES ('Admin'), ('Nhân viên');

-- Insert dữ liệu cho bảng NHOMQUYEN
INSERT INTO NHOMQUYEN (MAQ)
VALUES (1), (2);
-- Insert dữ liệu cho bảng NHANVIEN
INSERT INTO NHANVIEN (TENNV, NGAYSINH, TENTK, PASSNV, QUEQUAN, SDT, EMAIL, DIACHI, MANHOMPQ)
VALUES 
    (N'Nguyễn Văn A', '1990-01-01', 'nv_a', 'passwordA', N'Hà Nội', '0123456789', 'van.a@email.com', N'123 Đường ABC, Quận XYZ', 1),
    (N'Trần Thị B', '1995-02-15', 'tt_b', 'passwordB', N'Hồ Chí Minh', '0987654321', 'thi.b@email.com', N'456 Đường XYZ, Quận ABC', 2),
    (N'Lê Văn C', '1988-06-20', 'lv_c', 'passwordC', N'Đà Nẵng', '0123456780', 'van.c@email.com', N'789 Đường LMN, Quận OPQ', 2),
    (N'Phạm Thị D', '1992-11-10', 'pt_d', 'passwordD', N'Hải Phòng', '0909090909', 'thi.d@email.com', N'101 Đường PQR, Quận LMN', 2)

