//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET_QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MAHD { get; set; }
        public int MAPDP { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MADV { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUDATPHONG PHIEUDATPHONG { get; set; }
    }
}
