//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET_QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMQUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOMQUYEN()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int MANHOMPQ { get; set; }
        public Nullable<int> MAQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        public virtual PHANQUYEN PHANQUYEN { get; set; }
    }
}
